### PR TITLE
Fix compiler error with __attribute__((__noinline__))

### LINKED ISSUE #138: __noinline__ cannot be used in client code (occurs when building against libstdc++ v12)
When building the sources against libstdc++ v12 (v11 still works) there is a problem when compiling the CUDA examples due a macro define of _noinline_ and the fact that the shared_ptr_base.h header uses \_\_attribute\_\_((\_\_noinline\_\_)):

```
[ 80%] Building CXX object samples/cuda_samples/CMakeFiles/cuda-bandwidthTest.dir/1_Utilities/bandwidthTest/bandwidthTest.cu.o
In file included from /home/pjaaskel/src/chip-spv/samples/cuda_samples/1_Utilities/bandwidthTest/bandwidthTest.cu:31:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
      __attribute__((__noinline__))
                     ^
/home/pjaaskel/src/chip-spv/include/hip/spirv_hip.hh:40:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                    ^
In file included from /home/pjaaskel/src/chip-spv/samples/cuda_samples/1_Utilities/bandwidthTest/bandwidthTest.cu:31:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: type name does not allow function specifier to be specified
/home/pjaaskel/src/chip-spv/include/hip/spirv_hip.hh:40:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                    ^
In file included from /home/pjaaskel/src/chip-spv/samples/cuda_samples/1_Utilities/bandwidthTest/bandwidthTest.cu:31:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: expected expression
/home/pjaaskel/src/chip-spv/include/hip/spirv_hip.hh:40:46: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                             ^
3 errors generated when compiling for .
```

Are the #defines for these HIP keywords (still) necessary in spirv_hip.hh and hip_runtime.api.h or can we remove them? Shouldn't clang frontend bring those in when building in HIP mode?

### PR DESCRIPTION
**Pull request by linehill**
Fix a compiler error caused by C++ libraries (e.g. libstdc++ provided by g++-12) using `__attribute__((__noinline__))` in their code. Our definition of the `__noinline__` appears in the compilation as followed:

```
...
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:37: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
      __attribute__((__attribute__((noinline))))
...
```

For Clang <15 this issue is fixed by substituting the `__noinline__` with empty string and, therefore, rendering it ineffective, unfortunately. Fortunately, In Clang >=15 the `__noinline__` is a builtin keyword and the following use cases work in CUDA and HIP language modes:

```
__attribute__((__inline__)) void foo(...);
__inline__ void bar(...);
```
Fixes #138. 

Also, piggybacking a fix for hipcc missing headers when run in the build directory.

### CODE REVIEW

**Comment by pjaaskel** [comment]
Likely fixes #138?

**Comment by linehill** [comment]
> Likely fixes #138?

Seems like it should fix this.

File: tests/hiprtc/TestCommon.hh [hunk 1]
```diff
@@ -22,6 +22,9 @@
 
 #include <hip/hiprtc.h>
 #include <hip/hip_runtime_api.h>
+// TODO: Remove this header when it is included by the
+//       hip_runtime_api.h header.
+#include <hip/spirv_hip_host_defines.h>
```
Comment (pvelesko) [inline tests/hiprtc/TestCommon.hh:27]: Why include `hip_runtime_api.h` instead of `hip_runtime.h` ?

**Review by pvelesko — CHANGES_REQUESTED** [review]

File: tests/hiprtc/TestCommon.hh (hunk 1 above)
Comment (linehill) [reply tests/hiprtc/TestCommon.hh:27]: This header is meant to be compilable in C++ mode and non-hipcc compilers and the `hip_runtime_api.h` is suited for that (statement from the header: "This file can be compiled with a standard compiler.").

**Review by pvelesko — APPROVED** [review]
