### PR TITLE
Define __longlong_as_double() and __double_as_longlong()

### LINKED ISSUE #302: Use of `atomicAddDouble` crashed the kernel
Below is the output

```
CHIP debug [TID 20420] [1673650037.941151711] : Reading CHIP_PLATFORM from env
CHIP debug [TID 20420] [1673650037.941203491] : Reading CHIP_DEVICE_TYPE from env
CHIP debug [TID 20420] [1673650037.941229203] : Reading CHIP_DEVICE from env
CHIP debug [TID 20420] [1673650037.941233236] : Reading CHIP_BE from env
CHIP debug [TID 20420] [1673650037.941256881] : CHIP_PLATFORM=0
CHIP debug [TID 20420] [1673650037.941260296] : CHIP_DEVICE_TYPE=gpu
CHIP debug [TID 20420] [1673650037.941264000] : CHIP_DEVICE=0
CHIP debug [TID 20420] [1673650037.941267211] : CHIP_BE=default
CHIP debug [TID 20420] [1673650037.941271875] : CHIPDriver Initialize
CHIP debug [TID 20420] [1673650037.941279317] : CHIPBE=default... trying Level0 Backend
CHIP debug [TID 20420] [1673650037.941313740] : CHIPBackend Base Constructor
CHIP debug [TID 20420] [1673650037.958707903] : CHIPQueue() 0x55fe5186d9b0
CHIP debug [TID 20420] [1673650037.958962800] : 0x55fe51781970 CHIPContext::addDevice() 0x55fe5186d2c0
CHIP debug [TID 20420] [1673650037.959048912] : Thread Created with ID : 140532041545472
CHIP debug [TID 20420] [1673650037.959073676] : Thread Created with ID : 140532033152768
CHIP debug [TID 20420] [1673650037.959087827] : Reading CHIP_JIT_FLAGS from env
CHIP debug [TID 20420] [1673650037.959095200] : __hipRegisterFatBinary
CHIP debug [TID 20420] [1673650037.959182415] : Bundle entry ID 0 is: 'host-x86_64-unknown-linux'

CHIP debug [TID 20420] [1673650037.959206439] : Not a SPIR-V triple, ignoring

CHIP debug [TID 20420] [1673650037.959210681] : Bundle entry ID 1 is: 'hip-spirv64----generic'

CHIP debug [TID 20420] [1673650037.959780918] : Register module: 0x55fe5186be00

CHIP debug [TID 20420] [1673650037.959785999] : CHIPBackend->register_module()
CHIP debug [TID 20420] [1673650037.959824046] : RegisterFunction on module 0x55fe5186be00

CHIP debug [TID 20420] [1673650037.959830689] : RegisterFunction on 1 devices
CHIP debug [TID 20420] [1673650037.959833801] : CHIPBackend.registerFunctionAsKernel()
CHIP debug [TID 20420] [1673650037.960799345] : JIT compiler flags: -cl-std=CL2.0 -cl-take-global-address -cl-match-sincospi
CHIP error [TID 20420] [1673650038.048763196] : ZE Build Log:
error: undefined reference to `'
in function: '' called by kernel: 'process_batch_kernel(double, dbm_task_t const*, double const*, double const*, double*)'

error: backend compiler failed build.

error: undefined reference to `'
in function: '' called by kernel: 'process_batch_kernel(double, dbm_task_t const*, double const*, double const*, double*)'

error: backend compiler failed build.

CHIP error [TID 20420] [1673650038.048850190] : hipErrorTbd (ZE_RESULT_ERROR_MODULE_BUILD_FAILURE ) in /home/pvelesko/chip-spv/main/src/backend/Level0/CHIPBackendLevel0.cc:2145:compile

CHIP error [TID 20420] [1673650038.048978032] : hipErrorTbd
CHIP debug [TID 20420] [1673650038.049033917] : __hipRegisterFatBinary
CHIP debug [TID 20420] [1673650038.049044308] : Bundle entry ID 0 is: 'host-x86_64-unknown-linux'

CHIP debug [TID 20420] [1673650038.049048086] : Not a SPIR-V triple, ignoring

CHIP debug [TID 20420] [1673650038.049051574] : Bundle entry ID 1 is: 'hip-spirv64----generic'

CHIP debug [TID 20420] [1673650038.049079080] : Register module: 0x55fe51ad7600

CHIP debug [TID 20420] [1673650038.049096762] : CHIPBackend->register_module()
CHIP debug [TID 20420] [1673650038.049214898] : JIT compiler flags: -cl-std=CL2.0 -cl-take-global-address -cl-match-sincospi
CHIP debug [TID 20420] [1673650038.100844606] : __hipRegisterFatBinary
CHIP debug [TID 20420] [1673650038.100901023] : Bundle entry ID 0 is: 'host-x86_64-unknown-linux'

CHIP debug [TID 20420] [1673650038.100904898] : Not a SPIR-V triple, ignoring

CHIP debug [TID 20420] [1673650038.100908345] : Bundle entry ID 1 is: 'hip-spirv64----generic'

CHIP debug [TID 20420] [1673650038.100939824] : Register module: 0x55fe522541a0

CHIP debug [TID 20420] [1673650038.100943808] : CHIPBackend->register_module()
CHIP debug [TID 20420] [1673650038.101002690] : JIT compiler flags: -cl-std=CL2.0 -cl-take-global-address -cl-match-sincospi
CHIP debug [TID 20420] [1673650038.148943369] : __hipRegisterFatBinary
CHIP debug [TID 20420] [1673650038.149006718] : Bundle entry ID 0 is: 'host-x86_64-unknown-linux'

CHIP debug [TID 20420] [1673650038.149010851] : Not a SPIR-V triple, ignoring

CHIP debug [TID 20420] [1673650038.149014300] : Bundle entry ID 1 is: 'hip-spirv64----generic'

CHIP debug [TID 20420] [1673650038.149031509] : Register module: 0x55fe5239f450

CHIP debug [TID 20420] [1673650038.149035233] : CHIPBackend->register_module()
CHIP debug [TID 20420] [1673650038.149121628] : JIT compiler flags: -cl-std=CL2.0 -cl-take-global-address -cl-match-sincospi
CHIP debug [TID 20420] [1673650038.196785727] : __hipRegisterFatBinary
CHIP debug [TID 20420] [1673650038.196818952] : Bundle entry ID 0 is: 'host-x86_64-unknown-linux'

CHIP debug [TID 20420] [1673650038.196842168] : Not a SPIR-V triple, ignoring

CHIP debug [TID 20420] [1673650038.196845567] : Bundle entry ID 1 is: 'hip-spirv64----generic'

CHIP debug [TID 20420] [1673650038.196875133] : Register module: 0x55fe5350db10

CHIP debug [TID 20420] [1673650038.196878840] : CHIPBackend->register_module()
CHIP debug [TID 20420] [1673650038.196937587] : JIT compiler flags: -cl-std=CL2.0 -cl-take-global-address -cl-match-sincospi
OpenMP-threads: 8  GPUs: 1  Libxsmm: n/a  MPI: n/a

CHIP debug [TID 20420] [1673650038.608409984] : CHIPQueue() 0x55fe51a9db20
CHIP debug [TID 20420] [1673650038.608593089] : 0x55fe5186d2c0 CHIPDevice::addQueue(0x55fe51a9db20)
CHIP debug [TID 20420] [1673650038.608669590] : CHIPQueue 0x55fe51a9db20 added to the queue vector for device 0x55fe5186d2c0
CHIP debug [TID 20420] [1673650038.608734268] : Currently used memory on dev Intel(R) Iris(R) Pro Graphics P580 [0x193a]: 1 M

CHIP debug [TID 20420] [1673650038.608869648] : CHIPAllocationTracker::recordAllocation size: 1920000 HOST 0x0 DEV 0xffffd556aa610000 TYPE 1
CHIP debug [TID 20420] [1673650038.608905840] : CHIPQueue() 0x55fe51ae1d10
CHIP debug [TID 20420] [1673650038.608966655] : 0x55fe5186d2c0 CHIPDevice::addQueue(0x55fe51ae1d10)
CHIP debug [TID 20420] [1673650038.609000620] : CHIPQueue 0x55fe51ae1d10 added to the queue vector for device 0x55fe5186d2c0
CHIP debug [TID 20420] [1673650038.609033189] : Unregister module: 0x55fe5350db10

CHIP debug [TID 20420] [1673650038.609054697] : CHIPBackend->unregister_module()
CHIP debug [TID 20420] [1673650038.609098349] : __hipUnRegisterFatBinary 4


CHIP debug [TID 20420] [1673650038.609125643] : Unregister module: 0x55fe5239f450

CHIP debug [TID 20420] [1673650038.609146188] : CHIPBackend->unregister_module()
CHIP debug [TID 20420] [1673650038.609169914] : __hipUnRegisterFatBinary 3

CHIP debug [TID 20420] [1673650038.609190134] : Unregister module: 0x55fe522541a0

CHIP debug [TID 20420] [1673650038.609210340] : CHIPBackend->unregister_module()
CHIP debug [TID 20420] [1673650038.609232251] : __hipUnRegisterFatBinary 2

CHIP debug [TID 20420] [1673650038.609257169] : Unregister module: 0x55fe51ad7600

CHIP debug [TID 20420] [1673650038.609278522] : CHIPBackend->unregister_module()
CHIP debug [TID 20420] [1673650038.609298982] : __hipUnRegisterFatBinary 1

CHIP debug [TID 20420] [1673650038.609327512] : Unregister module: 0x55fe5186be00

CHIP debug [TID 20420] [1673650038.609353316] : CHIPBackend->unregister_module()
CHIP debug [TID 20420] [1673650038.609375115] : __hipUnRegisterFatBinary 0

CHIP debug [TID 20420] [1673650038.609396491] : Uninitializing CHIP...
CHIP debug [TID 20420] [1673650039.109707118] : Setting LastEvent for 0x55fe5186d9b0 0x0 -> 0x0
CHIP warning [TID 20420] [1673650039.109761853] : Not all user created streams have been destoyed... Queues remaining: 2
CHIP warning [TID 20420] [1673650039.109768875] : Make sure to call hipStreamDestroy() for all queues that have been created via hipStreamCreate()
CHIP warning [TID 20420] [1673650039.109771280] : Removing user-created streams without calling a destructor
CHIP debug [TID 20420] [1673650039.148248635] : CHIPBackend Destructor. Deleting all pointers.
CHIP debug [TID 20420] [1673650039.148351269] : 0x55fe51781970 CHIPContext.removeDevice() 0x55fe5186d2c0
CHIP debug [TID 20420] [1673650039.148370194] : ~CHIPDevice() 0x55fe5186d2c0
CHIP debug [TID 20420] [1673650039.148382915] : Setting LastEvent for 0x55fe5186d9b0 0x0 -> 0x0
CHIP debug [TID 20420] [1673650039.148391376] : Setting LastEvent for 0x55fe5186d9b0 0x0 -> 0x0
CHIP debug [TID 20420] [1673650039.148491189] : ~CHIPContext() 0x55fe51781970
From offload/offload_runtime.h:l115
```

### PR DESCRIPTION
**Pull request by linehill**
Fixes #302.

### CODE REVIEW

File: include/hip/devicelib/type_casting_intrinsics.hh [hunk 1]
```diff
@@ -98,4 +98,21 @@ EXPORT float __ull2float_rn(unsigned long long int x);
...
+
+EXPORT double __longlong_as_double(long long int x) {
+  static_assert(sizeof(double) == sizeof(long long), "");
+  double Tmp;
+  __builtin_memcpy(&Tmp, &x, sizeof(Tmp));
+  return Tmp;
+}
+
+#endif
+
```
Comment (pvelesko) [inline include/hip/devicelib/type_casting_intrinsics.hh:117]: It would make more sense for me that implementation would go into the implementation file (`devicelib.cl`) and we just leave headers here. The current state of the device library might be confusing so I could write a doc explaining it. In short, I wanted to split the device library into headers and implementations and get rid of all device library functions being implemented in macros (which was inherited from HIPLZ) and very difficult to read and/or debug individual functions. 

I emailed Rahul to get clarification as to why doesn't HIP provide these headers.

**Review by pvelesko — CHANGES_REQUESTED** [review]

File: include/hip/devicelib/type_casting_intrinsics.hh [hunk 2]
```diff
@@ -98,4 +96,9 @@ EXPORT float __ull2float_rn(unsigned long long int x);
 EXPORT float __ull2float_ru(unsigned long long int x);
 EXPORT float __ull2float_rz(unsigned long long int x);
 
+extern "C" {
+__device__ long long int __double_as_longlong(double x);
+__device__ double __longlong_as_double(long long int x);
+}
+
```
Comment (pvelesko) [inline include/hip/devicelib/type_casting_intrinsics.hh:103]: We should just modify the `EXPORT` macro if it's not correct.

**Review by pvelesko — CHANGES_REQUESTED** [review]

File: include/hip/devicelib/type_casting_intrinsics.hh (hunk 2 above)
Comment (linehill) [reply include/hip/devicelib/type_casting_intrinsics.hh:103]: I don’t dare to adjust the `EXPORT` macro just for these two functions. I don’t know which of the other device functions rely on the current macro definition and whether they are well tested for regressions coming from the change. Doesn’t seem like a worthwhile effort.

**Comment by linehill** [comment]
Rebased.

**Comment by pvelesko** [comment]
> I don’t dare to adjust the EXPORT macro just for these two functions. I don’t know which of the other device functions rely on the current macro definition and whether they are well tested for regressions coming from the change. Doesn’t seem like a worthwhile effort.

Ok. My next milestone involves device library improvements so if anything I can cleanup at that time.  LGTM after tests pass.

**Review by pvelesko — APPROVED** [review]
