### PR TITLE
Fix Level Zero Queue initialization

### LINKED ISSUE #207: [Level Zero] Unexpected sync between unrelated command queues
`TestStreamSemantics_2` 

1. submit work to a non-blocking queue
2. submit a memcopy to the default queue
3. memcopy executes a `CHIPQueue::finish()`
4. the finish() will not return until the callback is completed

### PR DESCRIPTION
**Pull request by pvelesko**
The L0 queue initialization was incorrect - always creating a copy queue even when one was unavailable. Fixes #207 

- [x] Fix the queue initialization process - combine two separate loops into one
- [x] Move queue ordinal properties and their getters into `CHIPDeviceLevel0`
- [x] Refactor `CHIPQueueLevel0::getNextComputeQueueDesc()` -> `CHIPDeviceLevel0::getNextComputeQueueDesc()`
- [x] `CHIPDeviceLevel0::getNextComputeQueueDesc()` respect queue priority
- [x] `CHIPDeviceLevel0::getNextCopyQueueDesc()` to use copy queue index iterator
- [x] `CHIPDeviceLevel0::getNextCopyQueueDesc()` check if copy queue is available\
- [x] Fix `maxMemoryFillPatternSize` checks
- [x] `CHIPQueueLevel0` add `LevelZeroQueueType::Compute/Copy`
    - [x] `CHIPQueueLevel0` include `MaxMemoryFillPatternSize`
    - [x] `CHIPQueueLevel0::getCmdList()` command list acquisition to only differentiate between immediate command lists and regular command lists
- [x] Create a follow-up PR for taking advantage of copy queues

### CODE REVIEW

**Comment by pvelesko** [comment]
@Sarbojit2019 Please review. The stream semantics sample is now passing for Level Zero.

File: src/backend/Level0/CHIPBackendLevel0.cc [hunk 1]
```diff
@@ -785,139 +820,98 @@ void CHIPQueueLevel0::initializeQueueGroupProperties() {
...
-  ZeCtx_ = ChipContextLz->get();
-  ZeDev_ = ChipDevLz->get();
+  assert(ComputeQueueGroupOrdinal_ > -1);
+  ze_command_queue_desc_t CommandQueueComputeDesc = getQueueDesc_(Priority);
+  CommandQueueComputeDesc.ordinal = ComputeQueueGroupOrdinal_;
 
-  initializeQueueGroupProperties();
+  auto MaxQueues = ComputeQueueProperties_.numQueues;
+  std::lock_guard<std::mutex> LockQueueIndexIterator(NextQueueIndexMtx_);
+  NextComputeQueueIndex_ = (NextComputeQueueIndex_ + 1) % MaxQueues;
```
Comment (Sarbojit2019) [inline src/backend/Level0/CHIPBackendLevel0.cc:900]: Missed index update CommandQueueComputeDesc.index = NextComputeQueueIndex_; and then increment. Both should be under lock.

File: src/backend/Level0/CHIPBackendLevel0.cc [hunk 2]
```diff
@@ -785,139 +820,98 @@ void CHIPQueueLevel0::initializeQueueGroupProperties() {
...
-  initializeComputeListImm();
-  initializeCopyListImm();
-#endif
+ze_command_queue_desc_t CHIPDeviceLevel0::getNextCopyQueueDesc(int Priority) {
+  assert(CopyQueueGroupOrdinal_ > -1);
+  ze_command_queue_desc_t CommandQueueCopyDesc = getQueueDesc_(Priority);
+  CommandQueueCopyDesc.ordinal = CopyQueueGroupOrdinal_;
+
+  auto MaxQueues = CopyQueueProperties_.numQueues;
+    std::lock_guard<std::mutex> LockQueueIndexIterator(NextQueueIndexMtx_);
```
Comment (Sarbojit2019) [inline src/backend/Level0/CHIPBackendLevel0.cc:911]: Alignment is off

File: src/backend/Level0/CHIPBackendLevel0.cc [hunk 3]
```diff
@@ -785,139 +820,98 @@ void CHIPQueueLevel0::initializeQueueGroupProperties() {
...
+  NextCopyQueueIndex_ = (NextCopyQueueIndex_ + 1) % MaxQueues;
```
Comment (Sarbojit2019) [inline src/backend/Level0/CHIPBackendLevel0.cc:912]: Missed index update CommandQueueCopyDesc.index = NextCopyQueueIndex_;

File: src/backend/Level0/CHIPBackendLevel0.cc [hunk 4]
```diff
@@ -694,72 +693,108 @@ CHIPEventLevel0 *CHIPQueueLevel0::getLastEvent() {
...
+    : CHIPQueueLevel0(ChipDev, Flags, L0_DEFAULT_QUEUE_PRIORITY,
+                      LevelZeroQueueType::Compute) {}
+
+CHIPQueueLevel0::CHIPQueueLevel0(CHIPDeviceLevel0 *ChipDev,
+                                 CHIPQueueFlags Flags, int Priority)
+    : CHIPQueueLevel0(ChipDev, Flags, Priority, LevelZeroQueueType::Compute) {}
+
+CHIPQueueLevel0::CHIPQueueLevel0(CHIPDeviceLevel0 *ChipDev,
+                                 CHIPQueueFlags Flags, int Priority,
+                                 LevelZeroQueueType TheType)
```
Comment (Sarbojit2019) [inline src/backend/Level0/CHIPBackendLevel0.cc:725]: What is the use of TheType? I thought CHIP_SPV maintains compute and copy descriptors(ordinal, index and other details) per queue so that based on workload it can choose one of them. Did we change it now?
If TheType is passed at the the time of construction then queue will be initialized with one type and moving to other may not be possible. Is my understanding correct?

**Review by Sarbojit2019 — CHANGES_REQUESTED** [review]
Minor bug and some suggestions.

File: src/backend/Level0/CHIPBackendLevel0.cc (hunk 1 above)
Comment (pvelesko) [reply src/backend/Level0/CHIPBackendLevel0.cc:900]: Index starts at 0 during initialization

File: src/backend/Level0/CHIPBackendLevel0.cc (hunk 4 above)
Comment (pvelesko) [reply src/backend/Level0/CHIPBackendLevel0.cc:725]: This PR ended up being much bigger than I expected currently the copy queues, if available, will not be used. I will implement this optimization in a subsequent PR.  @Sarbojit2019

Comment (pvelesko) [reply src/backend/Level0/CHIPBackendLevel0.cc:725]: > What is the use of TheType? I thought CHIP_SPV maintains compute and copy descriptors(ordinal, index and other details) per queue so that based on workload it can choose one of them. Did we change it now?

Yes we did. The descriptors for copy and compute live in the `CHIPDeviceLevel0` now. A Level Zero queue can now be either of compute type or copy type. Having multiple queues inside a single `CHIPQueue` will get confusing when having to sync queues, etc.

**Review by Sarbojit2019 — APPROVED** [review]
