### PR TITLE
Fix missing backend uninitialization causes occational crashes

### LINKED ISSUE #228: Occasional hipRTC Failure
```
Total Test time (real) =  11.86 sec

The following tests FAILED:
	  2 - TestHiprtcCPPKernels (SEGFAULT)
```
Had to run it for a while

### PR DESCRIPTION
**Pull request by linehill**
Missing backend uninitialization at program exit is known to cause crashes occasionally due to monitor threads being still in-flight and making references to destructed objects.

* Fix HIP programs without embedded modules (occasionally) crash at program exit.

* Make sure spdlog is destructed after the CHIP backend is uninitialized.

Fixes #228.

### CODE REVIEW

**Comment by pvelesko** [comment]
SYCL-HIP interop samples segfault
```
CHIPContextLevel0::~CHIPContextLevel0() {
  logTrace("~CHIPContextLevel0() {}", (void *)this);
  zeContextDestroy(this->ZeCtx); // segfault here
}
``` 

ran into this issue in #250

**Comment by pvelesko** [comment]
@linehill

File: src/CHIPBackend.hh [hunk 1]
```diff
@@ -1769,6 +1773,7 @@ public:
    * @return std::vector<std::string*>&
    */
   std::vector<std::string *> &getModulesStr();
+  const std::vector<std::string *> &getModulesStr() const;
```
Comment (pvelesko) [inline src/CHIPBackend.hh:1776]: Why do we need this

File: src/CHIPBackend.hh [hunk 2]
```diff
@@ -1789,6 +1794,10 @@ public:
    * @param mod_str
    */
   void unregisterModuleStr(std::string *ModuleStr);
+  size_t getNumRegisteredModules() const {
```
Comment (pvelesko) [inline src/CHIPBackend.hh:1797]: Why make this const? it puts a requirement on making `CHIPBackend::BackendMtx` mutable and adding a const-flavored version of `getModulesStr()`

File: src/CHIPBackend.cc [hunk 3]
```diff
@@ -1346,6 +1350,9 @@ size_t CHIPBackend::getNumDevices() {
   return NumDevices;
 }
 std::vector<std::string *> &CHIPBackend::getModulesStr() { return ModulesStr_; }
+const std::vector<std::string *> &CHIPBackend::getModulesStr() const {
+  return ModulesStr_;
+}
```
Comment (pvelesko) [inline src/CHIPBackend.cc:1355]: Seems unnecessary?

**Review by pvelesko — APPROVED** [review]

**Comment by pvelesko** [comment]
Rebased on main and a  few comments but looks good.

File: src/CHIPBackend.cc (hunk 3 above)
Comment (linehill) [reply src/CHIPBackend.cc:1355]: It's for calling the method via `const` qualified pointers and references.

File: src/CHIPBackend.hh (hunk 2 above)
Comment (linehill) [reply src/CHIPBackend.hh:1797]: I intend to communicate here that the method call does not change the state of the `CHIPBackend` instance which is **enforced by the compiler**. Although the `BackendMtx` is qualified as `mutable` (for enabling locking in this method), its state change is transient - the lock state returns to the original state after the call.

File: src/CHIPBackend.cc (hunk 3 above)
Comment (pvelesko) [reply src/CHIPBackend.cc:1355]: I meant that why have two of these? Why not get rid of the old non-const function and create a `addModulesStr()` and `removeModulesStr()` 

having a const and a non-const version of the same thing seems a bit redundant/confusing.

Comment (linehill) [reply src/CHIPBackend.cc]: Removed the getModuleStr.

**Comment by pvelesko** [comment]
@linehill next time please let me review before merging.
